[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.1", features = ["crossterm"] }
serde = { version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
slotmap = "1.0.7"
common = {path = "common"}
