services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: abn
      POSTGRES_PASSWORD: abn
      POSTGRES_DB: abn
    volumes:
      - ./server/database/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
    ports:
      - "5432:5432"
  server:
    build: .
    image: abn-server
    ports:
      - "8080:8080"
    command: [ "/usr/local/bin/server" ]
