[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = { version = "1.0.7", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
chrono = "0.4.35"
