@startuml
package "ABN server" {
    package "Postges DB"{
entity "Task" as task {
  +taskId : int <<generated>>
  --
  completed: boolean
  title : string
}

entity "DateProperty" as dateProp {
    + taskId : <<FK>>
    + name : string
  --
    date: timestamp
}
entity "TaskProperty" as taskProp {
    + taskId : <<FK>>
    + name : string
    --
    type: string
    numberVal : number | null
    stringVal : string | null
}
entity "Script" as script {
    + scriptId : int <<generated>>
    --
    script: string
}
entity "TaskScript" as taskScript {
    + taskId : <<FK>>
    + scriptId : <<FK>>
}
entity "TaskDependency" as taskDep {
    + taskId : <<FK>>
    + dependsOnTaskId : <<FK>>
}
}
package "API"{
    }
task }o--|| dateProp
task }o--|| taskProp
task ||--o{ taskScript
script ||--o{ taskScript
task ||--o{ taskDep

@enduml