name: Coverage
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: lcov report
        uses: kefasjw/lcov-pull-request-report@v1
        with:
          # Lcov file location. For example, coverage/lcov.info
          lcov-file: lcov.info
          # Github token required for getting list of changed files and posting comments
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Changed files minimum coverage in percentage. For example, 0, 50, 100
          # Default: 0
          changed-files-minimum-coverage: 90
