name: Clippy check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # this is required to get the full history

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Get changed files
      id: files
      run:         echo "::set-output name=modified::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.rs$' | xargs)"
      shell: bash
    - name: Show changed files
      run: echo "Modified files:${{ steps.files.outputs.modified }}"
    - name: Run clippy on changed files
      run: |
        for file in ${{ steps.files.outputs.modified }}; do
          cargo clippy -- $file || exit 1
        done
      shell: bash
