name: Clippy check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # this is required to get the full history

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true 

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
    - name: Run clippy on changed files
      run: |
        for file in ${{ steps.files.outputs.modified }}; do
          cargo clippy -- $file || exit 1
        done
      shell: bash
